services:
  mariadb:
    image: mariadb:10.3
    ports:
      - "3307:3306"
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - laravel_permissions

  phpMyAdmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8084:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    networks:
      - laravel_permissions

networks:
  laravel_permissions:
    driver: bridge